#!/bin/sh


CHANGED_PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep ".py\$")

if [ -z "$CHANGED_PYTHON_FILES" ]
then
   echo "No Python files found. No reason to run checks."
   exit 0
fi

set -e

pylint $CHANGED_PYTHON_FILES
black --check $CHANGED_PYTHON_FILES

echo "All checks successfully passed."